spring:
  profiles:
    group:
      server: production
    active: server
---
## 기본 서버 환경 설정

# Spring 관련
spring:
  config:
    activate:
      on-profile: production
  devtools:
    add-properties: false
  output:
    ansi:
      enabled: always

  # DataSource 설정
  main.allow-bean-definition-overriding: true
  sql.init.encoding: UTF-8
  datasource:
    hikari:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/?characterEncoding=utf-8
      username: devteller
      password: devteller123!

  data:
    redis:
      host: localhost
      port: 6379

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  liquibase:
    change-log: db/changelog.yaml
