name: test-compose
services:
  test-db:
    image: postgres:15.4
    environment:
      POSTGRES_USER: devteller
      POSTGRES_PASSWORD: devteller123!
    ports:
      - "5432:5432"
  test-redis:
    image: redis/redis-stack-server
    ports:
      - "6379:6379"
